//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lab4.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="lab4Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Ilab4Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain([NotNull] lab4Parser.MainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain([NotNull] lab4Parser.MainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] lab4Parser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] lab4Parser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.whiledo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhiledo([NotNull] lab4Parser.WhiledoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.whiledo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhiledo([NotNull] lab4Parser.WhiledoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.whilecondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilecondition([NotNull] lab4Parser.WhileconditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.whilecondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilecondition([NotNull] lab4Parser.WhileconditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.dobody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDobody([NotNull] lab4Parser.DobodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.dobody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDobody([NotNull] lab4Parser.DobodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] lab4Parser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] lab4Parser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] lab4Parser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] lab4Parser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.arifmoperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArifmoperation([NotNull] lab4Parser.ArifmoperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.arifmoperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArifmoperation([NotNull] lab4Parser.ArifmoperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.typedata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedata([NotNull] lab4Parser.TypedataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.typedata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedata([NotNull] lab4Parser.TypedataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst([NotNull] lab4Parser.ConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst([NotNull] lab4Parser.ConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lab4Parser.operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperands([NotNull] lab4Parser.OperandsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lab4Parser.operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperands([NotNull] lab4Parser.OperandsContext context);
}
