//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Javalib\lab4.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class lab4Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WS=1, Typenumber=2, Typereal=3, Typechar=4, Typebool=5, Constnumber=6, 
		Constreal=7, Constchar=8, Constbool=9, Constseven=10, Exp=11, ArifmOp=12, 
		ArifmOpExt=13, LogOp=14, LbParam=15, RbParam=16, LfBracket=17, RfBracket=18, 
		LineSep=19, Prisv=20, IdentSep=21, While=22, Do=23, End=24, Ident=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WS", "Typenumber", "Typereal", "Typechar", "Typebool", "Constnumber", 
		"Constreal", "Constchar", "Constbool", "Constseven", "Exp", "ArifmOp", 
		"ArifmOpExt", "LogOp", "LbParam", "RbParam", "LfBracket", "RfBracket", 
		"LineSep", "Prisv", "IdentSep", "While", "Do", "End", "Ident"
	};


	public lab4Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public lab4Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'number'", "'real'", null, "'bool'", null, null, null, null, 
		null, null, null, null, null, "'('", "')'", "'{'", "'}'", "';'", "':='", 
		"','", "'while'", "'do'", "'end'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WS", "Typenumber", "Typereal", "Typechar", "Typebool", "Constnumber", 
		"Constreal", "Constchar", "Constbool", "Constseven", "Exp", "ArifmOp", 
		"ArifmOpExt", "LogOp", "LbParam", "RbParam", "LfBracket", "RfBracket", 
		"LineSep", "Prisv", "IdentSep", "While", "Do", "End", "Ident"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lab4.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static lab4Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xF7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', 
		'\x5', 'm', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x6', '\a', 'u', '\n', '\a', '\r', 
		'\a', '\xE', '\a', 'v', '\x3', '\b', '\x6', '\b', 'z', '\n', '\b', '\r', 
		'\b', '\xE', '\b', '{', '\x3', '\b', '\x3', '\b', '\a', '\b', '\x80', 
		'\n', '\b', '\f', '\b', '\xE', '\b', '\x83', '\v', '\b', '\x3', '\b', 
		'\x5', '\b', '\x86', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x6', '\b', 
		'\x8A', '\n', '\b', '\r', '\b', '\xE', '\b', '\x8B', '\x3', '\b', '\x5', 
		'\b', '\x8F', '\n', '\b', '\x3', '\b', '\x6', '\b', '\x92', '\n', '\b', 
		'\r', '\b', '\xE', '\b', '\x93', '\x3', '\b', '\x5', '\b', '\x97', '\n', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', 
		'\n', '\xA3', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', 
		'\v', '\xA8', '\n', '\v', '\f', '\v', '\xE', '\v', '\xAB', '\v', '\v', 
		'\x3', '\f', '\x3', '\f', '\x5', '\f', '\xAF', '\n', '\f', '\x3', '\f', 
		'\x6', '\f', '\xB2', '\n', '\f', '\r', '\f', '\xE', '\f', '\xB3', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x5', '\xE', '\xBC', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\xCA', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', '\xEB', '\n', 
		'\x1A', '\f', '\x1A', '\xE', '\x1A', '\xEE', '\v', '\x1A', '\x3', '\x1A', 
		'\a', '\x1A', '\xF1', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xF4', 
		'\v', '\x1A', '\x5', '\x1A', '\xF6', '\n', '\x1A', '\x2', '\x2', '\x1B', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x3', '\x2', '\b', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x5', '\x2', '\x32', 
		';', '\x43', '\\', '\x63', '|', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', 
		'\x2', '-', '-', '/', '/', '\x5', '\x2', ',', '-', '/', '/', '\x31', '\x31', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x2', '\x111', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x35', '\x3', '\x2', '\x2', '\x2', '\x5', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\a', '@', '\x3', '\x2', '\x2', '\x2', '\t', 'l', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'n', '\x3', '\x2', '\x2', '\x2', '\r', 
		't', '\x3', '\x2', '\x2', '\x2', '\xF', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x98', '\x3', '\x2', '\x2', '\x2', '\x13', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\xA4', '\x3', '\x2', '\x2', '\x2', '\x17', '\xAC', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\xBB', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xC9', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\xCB', '\x3', '\x2', '\x2', '\x2', '!', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '#', '\xCF', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xD1', '\x3', '\x2', '\x2', '\x2', '\'', '\xD3', '\x3', '\x2', '\x2', 
		'\x2', ')', '\xD5', '\x3', '\x2', '\x2', '\x2', '+', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '-', '\xDA', '\x3', '\x2', '\x2', '\x2', '/', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\xE3', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\xE7', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\t', '\x2', '\x2', 
		'\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\b', 
		'\x2', '\x2', '\x2', '\x38', '\x4', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\a', 'p', '\x2', '\x2', ':', ';', '\a', 'w', '\x2', '\x2', ';', 
		'<', '\a', 'o', '\x2', '\x2', '<', '=', '\a', '\x64', '\x2', '\x2', '=', 
		'>', '\a', 'g', '\x2', '\x2', '>', '?', '\a', 't', '\x2', '\x2', '?', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', 't', '\x2', '\x2', 
		'\x41', '\x42', '\a', 'g', '\x2', '\x2', '\x42', '\x43', '\a', '\x63', 
		'\x2', '\x2', '\x43', '\x44', '\a', 'n', '\x2', '\x2', '\x44', '\b', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x65', '\x2', '\x2', '\x46', 
		'G', '\a', 'j', '\x2', '\x2', 'G', 'H', '\a', '\x63', '\x2', '\x2', 'H', 
		'm', '\a', 't', '\x2', '\x2', 'I', 'J', '\a', '\x65', '\x2', '\x2', 'J', 
		'K', '\a', 'j', '\x2', '\x2', 'K', 'L', '\a', '\x63', '\x2', '\x2', 'L', 
		'M', '\a', 't', '\x2', '\x2', 'M', 'm', '\a', '\x63', '\x2', '\x2', 'N', 
		'O', '\a', '\x65', '\x2', '\x2', 'O', 'P', '\a', 'j', '\x2', '\x2', 'P', 
		'Q', '\a', '\x63', '\x2', '\x2', 'Q', 'R', '\a', 't', '\x2', '\x2', 'R', 
		'S', '\a', '\x63', '\x2', '\x2', 'S', 'm', '\a', '\x65', '\x2', '\x2', 
		'T', 'U', '\a', '\x65', '\x2', '\x2', 'U', 'V', '\a', 'j', '\x2', '\x2', 
		'V', 'W', '\a', '\x63', '\x2', '\x2', 'W', 'X', '\a', 't', '\x2', '\x2', 
		'X', 'Y', '\a', '\x63', '\x2', '\x2', 'Y', 'Z', '\a', '\x65', '\x2', '\x2', 
		'Z', 'm', '\a', 'v', '\x2', '\x2', '[', '\\', '\a', '\x65', '\x2', '\x2', 
		'\\', ']', '\a', 'j', '\x2', '\x2', ']', '^', '\a', '\x63', '\x2', '\x2', 
		'^', '_', '\a', 't', '\x2', '\x2', '_', '`', '\a', '\x63', '\x2', '\x2', 
		'`', '\x61', '\a', '\x65', '\x2', '\x2', '\x61', '\x62', '\a', 'v', '\x2', 
		'\x2', '\x62', 'm', '\a', 'g', '\x2', '\x2', '\x63', '\x64', '\a', '\x65', 
		'\x2', '\x2', '\x64', '\x65', '\a', 'j', '\x2', '\x2', '\x65', '\x66', 
		'\a', '\x63', '\x2', '\x2', '\x66', 'g', '\a', 't', '\x2', '\x2', 'g', 
		'h', '\a', '\x63', '\x2', '\x2', 'h', 'i', '\a', '\x65', '\x2', '\x2', 
		'i', 'j', '\a', 'v', '\x2', '\x2', 'j', 'k', '\a', 'g', '\x2', '\x2', 
		'k', 'm', '\a', 't', '\x2', '\x2', 'l', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'l', 'I', '\x3', '\x2', '\x2', '\x2', 'l', 'N', '\x3', '\x2', '\x2', '\x2', 
		'l', 'T', '\x3', '\x2', '\x2', '\x2', 'l', '[', '\x3', '\x2', '\x2', '\x2', 
		'l', '\x63', '\x3', '\x2', '\x2', '\x2', 'm', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'o', '\a', '\x64', '\x2', '\x2', 'o', 'p', '\a', 'q', '\x2', 
		'\x2', 'p', 'q', '\a', 'q', '\x2', '\x2', 'q', 'r', '\a', 'n', '\x2', 
		'\x2', 'r', '\f', '\x3', '\x2', '\x2', '\x2', 's', 'u', '\x4', '\x32', 
		';', '\x2', 't', 's', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', 
		'\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', 
		'\x2', '\x2', 'w', '\xE', '\x3', '\x2', '\x2', '\x2', 'x', 'z', '\x4', 
		'\x32', ';', '\x2', 'y', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', 
		'\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', 
		'\x2', '\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '\x81', 
		'\a', '\x30', '\x2', '\x2', '~', '\x80', '\x4', '\x32', ';', '\x2', '\x7F', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x85', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x86', '\x5', '\x17', '\f', 
		'\x2', '\x85', '\x84', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x97', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x89', '\a', '\x30', '\x2', '\x2', '\x88', '\x8A', '\x4', '\x32', ';', 
		'\x2', '\x89', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8F', '\x5', '\x17', '\f', '\x2', '\x8E', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\x4', '\x32', ';', 
		'\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x97', '\x5', '\x17', '\f', '\x2', '\x96', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x87', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x97', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\a', ')', '\x2', '\x2', '\x99', '\x9A', '\t', 
		'\x3', '\x2', '\x2', '\x9A', '\x9B', '\a', ')', '\x2', '\x2', '\x9B', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\a', 'N', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', '\x61', '\x2', '\x2', '\x9E', '\xA3', '\a', 
		'V', '\x2', '\x2', '\x9F', '\xA0', '\a', 'N', '\x2', '\x2', '\xA0', '\xA1', 
		'\a', '\x61', '\x2', '\x2', '\xA1', '\xA3', '\a', 'H', '\x2', '\x2', '\xA2', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\xA2', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\x14', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'U', '\x2', '\x2', '\xA5', '\xA9', '\x4', '\x33', '\x38', '\x2', '\xA6', 
		'\xA8', '\x4', '\x32', '\x38', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAE', '\t', '\x4', '\x2', '\x2', '\xAD', '\xAF', '\t', 
		'\x5', '\x2', '\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xB2', '\x4', '\x32', ';', '\x2', '\xB1', '\xB0', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\xB4', '\x18', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\t', 
		'\x6', '\x2', '\x2', '\xB6', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', '-', '\x2', '\x2', '\xB8', '\xBC', '\a', '-', '\x2', '\x2', 
		'\xB9', '\xBA', '\a', '/', '\x2', '\x2', '\xBA', '\xBC', '\a', '/', '\x2', 
		'\x2', '\xBB', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\a', '\x63', '\x2', '\x2', '\xBE', '\xBF', '\a', 'p', '\x2', 
		'\x2', '\xBF', '\xCA', '\a', '\x66', '\x2', '\x2', '\xC0', '\xC1', '\a', 
		'q', '\x2', '\x2', '\xC1', '\xCA', '\a', 't', '\x2', '\x2', '\xC2', '\xCA', 
		'\x4', '>', '@', '\x2', '\xC3', '\xC4', '\a', '#', '\x2', '\x2', '\xC4', 
		'\xCA', '\a', '?', '\x2', '\x2', '\xC5', '\xC6', '\a', '>', '\x2', '\x2', 
		'\xC6', '\xCA', '\a', '?', '\x2', '\x2', '\xC7', '\xC8', '\a', '@', '\x2', 
		'\x2', '\xC8', '\xCA', '\a', '?', '\x2', '\x2', '\xC9', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xCA', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xCC', '\a', '*', '\x2', '\x2', '\xCC', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\xCD', '\xCE', '\a', '+', '\x2', '\x2', '\xCE', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\a', '}', '\x2', '\x2', '\xD0', '$', '\x3', '\x2', 
		'\x2', '\x2', '\xD1', '\xD2', '\a', '\x7F', '\x2', '\x2', '\xD2', '&', 
		'\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', '=', '\x2', '\x2', '\xD4', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\a', '<', '\x2', '\x2', 
		'\xD6', '\xD7', '\a', '?', '\x2', '\x2', '\xD7', '*', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\xD9', '\a', '.', '\x2', '\x2', '\xD9', ',', '\x3', '\x2', 
		'\x2', '\x2', '\xDA', '\xDB', '\a', 'y', '\x2', '\x2', '\xDB', '\xDC', 
		'\a', 'j', '\x2', '\x2', '\xDC', '\xDD', '\a', 'k', '\x2', '\x2', '\xDD', 
		'\xDE', '\a', 'n', '\x2', '\x2', '\xDE', '\xDF', '\a', 'g', '\x2', '\x2', 
		'\xDF', '.', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\a', '\x66', 
		'\x2', '\x2', '\xE1', '\xE2', '\a', 'q', '\x2', '\x2', '\xE2', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\a', 'g', '\x2', '\x2', '\xE4', 
		'\xE5', '\a', 'p', '\x2', '\x2', '\xE5', '\xE6', '\a', '\x66', '\x2', 
		'\x2', '\xE6', '\x32', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', '\t', 
		'\a', '\x2', '\x2', '\xE8', '\xF5', '\x4', '\x32', ';', '\x2', '\xE9', 
		'\xEB', '\t', '\a', '\x2', '\x2', '\xEA', '\xE9', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\xEC', '\xED', '\x3', '\x2', '\x2', '\x2', '\xED', 
		'\xF6', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\xEF', '\xF1', '\x4', '\x32', ';', '\x2', '\xF0', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\xF1', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF2', 
		'\xF0', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', '\xF3', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\xF5', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xF5', 
		'\xF2', '\x3', '\x2', '\x2', '\x2', '\xF6', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x2', 'l', 'v', '{', '\x81', '\x85', '\x8B', '\x8E', '\x93', 
		'\x96', '\xA2', '\xA9', '\xAE', '\xB3', '\xBB', '\xC9', '\xEC', '\xF2', 
		'\xF5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
